import path from 'node:path';
import { formatInTimeZone } from 'date-fns-tz';
import type { CompletedSession, FocusMetrics, WorkEvent } from './types.js';
import { computeFocusMetrics, groupSessions } from './summary.js';
import { formatDuration, formatDurationHuman } from '../storage/markdownRenderer.js';
import {
  escapeMarkdownInline,
  formatTags,
  limitString,
} from '../storage/markdownSanitize.js';

export type ExportFormat = 'csv' | 'json' | 'standup' | 'weekly' | 'obsidian';

export interface ExportResult {
  format: ExportFormat;
  mimeType: string;
  content: string;
  byline: string;
}

export interface ExportInputData {
  format: ExportFormat;
  sessions: CompletedSession[];
  events: WorkEvent[];
  timezone: string;
  periodLabel: string;
  groupBy: 'task' | 'project' | 'ticket' | 'tag' | 'day';
}

const BYLINE = 'Generated by Sugukuru WorkClock MCP';

export function buildExport(input: ExportInputData): ExportResult {
  switch (input.format) {
    case 'csv':
      return { format: 'csv', mimeType: 'text/csv', content: toCsv(input), byline: BYLINE };
    case 'json':
      return {
        format: 'json',
        mimeType: 'application/json',
        content: toJson(input),
        byline: BYLINE,
      };
    case 'standup':
      return {
        format: 'standup',
        mimeType: 'text/markdown',
        content: toStandup(input),
        byline: BYLINE,
      };
    case 'weekly':
      return {
        format: 'weekly',
        mimeType: 'text/markdown',
        content: toWeekly(input),
        byline: BYLINE,
      };
    case 'obsidian':
      return {
        format: 'obsidian',
        mimeType: 'text/markdown',
        content: toObsidian(input),
        byline: BYLINE,
      };
  }
}

function toCsv(input: ExportInputData): string {
  const header = [
    'date',
    'start',
    'end',
    'durationMinutes',
    'task',
    'project',
    'ticket',
    'tags',
    'outcome',
    'note',
  ].join(',');

  const rows = input.sessions.map((session) => {
    const date = formatInTimeZone(new Date(session.startedAtEpochMs), input.timezone, 'yyyy-MM-dd');
    const start = formatInTimeZone(new Date(session.startedAtEpochMs), input.timezone, 'HH:mm');
    const end = formatInTimeZone(new Date(session.endedAtEpochMs), input.timezone, 'HH:mm');
    return [
      date,
      start,
      end,
      String(Math.round(session.totalActiveMs / 60_000)),
      csvCell(session.taskName),
      csvCell(session.project ?? ''),
      csvCell(session.ticket ?? ''),
      csvCell(session.tags.join(' ')),
      csvCell(session.outcome ?? ''),
      csvCell(session.note ?? ''),
    ].join(',');
  });

  return [header, ...rows].join('\n');
}

function csvCell(value: string): string {
  const cleaned = limitString(value, 500);
  if (/[",\n]/.test(cleaned)) {
    return `"${cleaned.replace(/"/g, '""')}"`;
  }
  return cleaned;
}

function toJson(input: ExportInputData): string {
  const metrics = computeFocusMetrics(input.sessions, input.events);
  return JSON.stringify(
    {
      generatedBy: BYLINE,
      schemaVersion: 1,
      period: input.periodLabel,
      timezone: input.timezone,
      metrics,
      sessions: input.sessions.map((session) => ({
        id: session.id,
        taskName: session.taskName,
        project: session.project,
        ticket: session.ticket,
        tags: session.tags,
        startedAtIso: session.startedAtIso,
        endedAtIso: session.endedAtIso,
        totalActiveMs: session.totalActiveMs,
        outcome: session.outcome,
        note: session.note,
      })),
    },
    null,
    2,
  );
}

function toStandup(input: ExportInputData): string {
  const byTask = groupSessions(input.sessions, 'task', input.timezone);
  const metrics = computeFocusMetrics(input.sessions, input.events);
  const lines: string[] = [];
  lines.push(`# 日報 (${input.periodLabel})`);
  lines.push('');
  lines.push('## やったこと');
  if (byTask.length === 0) {
    lines.push('- (記録なし)');
  }
  for (const group of byTask) {
    lines.push(`- ${escapeMarkdownInline(group.key)} — ${formatDurationHuman(group.totalActiveMs)}`);
  }
  lines.push('');
  lines.push('## サマリー');
  lines.push(`- 合計稼働: ${formatDurationHuman(metrics.totalActiveMs)}`);
  lines.push(`- セッション数: ${metrics.sessionCount}`);
  lines.push(`- 中断回数: ${metrics.interruptionCount}`);
  lines.push(`- 最長集中: ${formatDurationHuman(metrics.longestFocusBlockMs)}`);
  lines.push('');
  lines.push(byline());
  return lines.join('\n');
}

function toWeekly(input: ExportInputData): string {
  const metrics = computeFocusMetrics(input.sessions, input.events);
  const groups = groupSessions(input.sessions, input.groupBy, input.timezone);
  const byDay = groupSessions(input.sessions, 'day', input.timezone);
  const lines: string[] = [];
  lines.push(`# 週報 (${input.periodLabel})`);
  lines.push('');
  lines.push(`合計: ${formatDurationHuman(metrics.totalActiveMs)} / ${metrics.sessionCount} sessions`);
  lines.push('');
  lines.push(`## ${input.groupBy} 別`);
  for (const group of groups) {
    lines.push(`- ${escapeMarkdownInline(group.key)}: ${formatDurationHuman(group.totalActiveMs)}`);
  }
  lines.push('');
  lines.push('## 日別');
  for (const day of byDay.sort((a, b) => a.key.localeCompare(b.key))) {
    lines.push(`- ${day.key}: ${formatDuration(day.totalActiveMs)}`);
  }
  lines.push('');
  lines.push(byline());
  return lines.join('\n');
}

function toObsidian(input: ExportInputData): string {
  const lines: string[] = [];
  lines.push('---');
  lines.push('tags: [worklog]');
  lines.push(`period: ${input.periodLabel}`);
  lines.push('---');
  lines.push('');
  lines.push(`# WorkLog ${input.periodLabel}`);
  lines.push('');
  for (const session of input.sessions) {
    const date = formatInTimeZone(new Date(session.startedAtEpochMs), input.timezone, 'yyyy-MM-dd HH:mm');
    const task = `[[${sanitizeWikiLink(session.taskName)}]]`;
    const project = session.project ? ` ([[${sanitizeWikiLink(session.project)}]])` : '';
    const ticket = session.ticket ? ` ${session.ticket}` : '';
    const tags = session.tags.length ? ` ${formatTags(session.tags)}` : '';
    lines.push(`- ${date} ${task}${project}${ticket} — ${formatDurationHuman(session.totalActiveMs)}${tags}`);
  }
  lines.push('');
  lines.push(byline());
  return lines.join('\n');
}

function sanitizeWikiLink(value: string): string {
  return limitString(value, 120).replace(/[[\]|#^]/g, ' ').trim() || 'untitled';
}

function byline(): string {
  return `> ${BYLINE}`;
}

export function exportFileRelativePath(format: ExportFormat, periodLabel: string): string {
  const ext = format === 'csv' ? 'csv' : format === 'json' ? 'json' : 'md';
  const safeLabel =
    periodLabel
      .replace(/[\\/]+/g, '-')
      .replace(/\.{2,}/g, '-')
      .replace(/[^0-9a-zA-Z._-]+/g, '-')
      .replace(/^[.-]+|[.-]+$/g, '') || 'export';
  return path.join('exports', `${format}-${safeLabel}.${ext}`);
}

export type { CompletedSession, FocusMetrics };
